name: Mutation Test Rich Module

on:
  pull_request:
  push:
    branches:
      - master



jobs:
  mutation-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.1.4
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Test with pytest
        run: pytest --junitxml=report.xml tests/ -vv
      - name: Mutation Test
        run: make mutation-test
      # - name: Generate Report
      #   run: mutmut junitxml --suspicious-policy=ignore --untested-policy=ignore > mutation-report.xml
      - name: Publish Mutation Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: report.xml
